### ISSUE TITLE
Random env seed for multi-processes training on habitat v0.1.6

### ISSUE THREAD

**Issue by PatZhuang** [jacobkrantz/VLN-CE#10]
So habitat v0.1.6 removes the third parameter of `make_env_fn` which is served as the parameter for the `env.seed()` function, instead the `env.seed()` takes `env.config.TASK_CONFIG.SEED` as its parameter.

I wonder if this breaks any training scheme for the `env.config.TASK_CONFIG.SEED` is a constant integer (default is 100) but in your implementation you used process number which is different for each process. If so, how can I fix this?

**Comment by jacobkrantz** [comment]
The VLN-CE codebase officially supports Habitat 0.1.5 right now. But if you want to extend it to Habitat 0.1.6, then accounting for this seed is important. The relevant hab-lab change is [this PR](https://github.com/facebookresearch/habitat-lab/pull/405). 

You will still want to set the seed of each environment based on the unique process number, which can be done before this line:
https://github.com/jacobkrantz/VLN-CE/blob/163af64c013e8274a68af1d13f5115d893a82c33/vlnce_baselines/common/env_utils.py#L64

Adding this line should do it:
```python
task_config.SEED = task_config.SEED + i
```
