### ISSUE TITLE
what are _gt files for rxr?

### ISSUE THREAD

**Issue by volkancirik** [jacobkrantz/VLN-CE#12]
Hello,

When I pull all data for rxr, I do not get _gt files. what are {train,val_seen,val_unseen}_guide_gt.json.gz files? Where do I get them?

**Comment by volkancirik** [comment]
we're supposed to use [this link](https://storage.googleapis.com/rxr-habitat/RxR_VLNCE_v0.zip). Before closing this issue, I'm curious what are _gt files? how do you generate them?

**Comment by jacobkrantz** [comment]
Hi Volkan,

The data and starter code for the RxR-Habitat Challenge are located in the `rxr-habitat-challenge` [branch](https://github.com/jacobkrantz/VLN-CE/tree/rxr-habitat-challenge).
You can find the data to download in the [README](https://github.com/jacobkrantz/VLN-CE/tree/rxr-habitat-challenge#data). That link currently is https://storage.googleapis.com/rxr-habitat/RxR_VLNCE_v0.zip

The `{split}_guide.json.gz` files define each episode, containing the starting location/heading, the goal location, and the instruction. They also contain a `referece_path`, which is the sequence of node locations visited by the oracle agent in the original RxR-MP3D.
To provide oracle paths in RxR-Habitat, we run a shortest-path-follower in Habitat that navigates to each node in the `referece_path`. We save the resulting trajectory to the file `{split}_guide_gt.json.gz` (gt = ground truth).

**Comment by volkancirik** [comment]
Cool! Thanks for the prompt response!
