### ISSUE TITLE
[RxR-Habitat] What kind of GPU is needed to train the cma policy with the original config?

### ISSUE THREAD

**Issue by wz0919** [jacobkrantz/VLN-CE#17]
Hi there,

While running the starter code for the rxr challenge I found a single NVIDIA 2080ti GPU's VRAM (11GiB) could only fit `batch_size` 1 with the cma policy and `max_traj_len` 250. Although we could set `effective_batch_size` but it is set to be -1 while `batch_size` to be 3 in the original config. So I'm wondering what kind of GPU is needed to train the cma policy with the original config?

Also, I found with `batch_size` 1, `max_traj_len` 250, `preload_size` 30 and 9 environments simulated, the used RAM will be more that 40 GiB. Is it normal?

Thanks!

**Comment by yifan123** [comment]
Hello, I have the same problem. Would you like to share some useful information? Thx

**Comment by jacobkrantz** [comment]
We trained the baseline models with GPUs that had 16GB VRAM. We used the exact config specified [here](https://github.com/jacobkrantz/VLN-CE/blob/52a478259ae41068eecb751a0cc49307384e460b/vlnce_baselines/config/rxr_configs/rxr_cma_en.yaml) in the starter code. The only change we made was to scale up `NUM_ENVIRONMENTS` to one less than the number of CPU cores available. In our case that was 9. If you want to replicate results with a batch size of 3 but do not have the VRAM to do so, setting `batch_size: 1` and `effective_batch_size: 3` will work, albeit with a speed tradeoff.

40GB regular RAM sounds reasonable. If you are constrained by RAM, then cutting down the `preload_size` should help while not hurting speed too much.

**Comment by yifan123** [comment]
Hi, I changed
* _C.IL.batch_size = 1 in vlnce_baselines/config/default.py#L58
* _C.IL.RECOLLECT_TRAINER.effective_batch_size = 3 in vlnce_baselines/config/default.py#L82
* batch_size: 1 in vlnce_baselines/config/rxr_configs/rxr_cma_en.yaml#L31
However, when I run
`python run.py --exp-config vlnce_baselines/config/rxr_configs/rxr_cma_en.yaml --run-type train`
I also meet CUDA out of memeory error.  Do I modify the config in the right way? Thx
