### ISSUE TITLE
[RxR-Habitat] Eval baseline reproduction

### ISSUE THREAD

**Issue by nikwalia** [jacobkrantz/VLN-CE#24]
Hello,
I tried to reproduce the baseline performance using the same `yaml` file listed on the README-
```
python run.py \
  --exp-config vlnce_baselines/config/rxr_configs/rxr_cma_en.yaml \
  --run-type train
```
My experimental setup used 4 TITAN X GPUs with 4 environments each. Referring issue #17 , I set my `batch_size: 1` and `effective_batch_size: 3` to successfully train. No other changes have been made to the codebase.

After evaluating my saved checkpoint, I found the following metrics (all average across episodes):
> steps_taken: 350.443718
> path_length: 6.737881
> distance_to_goal: 11.082229
> success: 0.066503
> oracle_success: 0.180703
> spl: 0.055868
> ndtw: 0.358719

Comparing these to Table 2 entry for Seq2Seq w/ RGBD, Instructions, and History, I found my performance to be significantly lower for the matching metrics.

Is this the right config to be used to match the relevant baseline?

**Comment by jacobkrantz** [comment]
>Comparing these to Table 2 entry for Seq2Seq w/ RGBD

Those Table 2 models were trained and evaluated on the VLN-CE dataset which uses the Room-to-Room dataset from VLN. The config files you are using here are for Room-across-Room, which has a different distribution of episodes and has a modified task configuration.

If you are trying to reproduce the baseline model results of the RxR-Habitat Challenge (the Room-across-Room data), here are some numbers for comparison. After training using `rxr_cma_en.yaml`, the best checkpoint (ckpt.4.pth) on English val-unseen achieved:
```json
{
    "steps_taken": 168.4,
    "path_length": 7.099,
    "distance_to_goal": 10.57,
    "success": 0.1404,
    "oracle_success": 0.2172,
    "spl": 12.26,
    "ndtw": 0.4034
}
```
