### ISSUE TITLE
'RuntimeError: No scenes to load...' when using recollect_trainer

### ISSUE THREAD

**Issue by RavenKiller** [jacobkrantz/VLN-CE#27]
When I trained my model with `TRAINER_NAME` set to recollect_trainer, I got the error:
```
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    main()
  File "run.py", line 43, in main
    run_exp(**vars(args))
  File "run.py", line 84, in run_exp
    trainer.train()
  File "/home/raven/hzt/vln-ce/vlnce_baselines/recollect_trainer.py", line 77, in train
    dataset = TeacherRecollectionDataset(self.config)
  File "/home/raven/hzt/vln-ce/vlnce_baselines/common/recollection_dataset.py", line 49, in __init__
    self.initialize_sims()
  File "/home/raven/hzt/vln-ce/vlnce_baselines/common/recollection_dataset.py", line 60, in initialize_sims
    episodes_allowed=list(self.trajectories.keys()),
  File "/home/raven/hzt/vln-ce/vlnce_baselines/common/env_utils.py", line 51, in construct_envs
    "No scenes to load, multi-process logic relies on being able"
RuntimeError: No scenes to load, multi-process logic relies on being able to split scenes uniquely between processes
```
I traced the error back to _habitat_extensions/task.py_ and found that `self.episodes` in `VLNCEDatasetV1` class was empty after initializing. The cause seems to be different data types between elements in `config.EPISODES_ALLOWED` and `episode_id` in `self.episodes`.

---
My temporary solution is converting allowed episode ids to integers before passing them to `construct_envs` (line 57-61 in _vlnce_baselines/common/recollection_dataset.py_):
```
        self.envs = construct_envs(
            config,
            get_env_class(config.ENV_NAME),
            episodes_allowed=[int(v) for v in self.trajectories.keys()],
        )
```

**Comment by jacobkrantz** [comment]
Hi @RavenKiller, thanks for identifying this issue. I confirmed it with configs that use the R2R dataset with the RecollectTrainer. Configs that use RxR work fine for me. Your temporary solution fixes the issue for R2R but happens to break RxR. The solution is to re-define R2R episode IDs as strings so they both work. The above merge commit applies this fix.
