### ISSUE TITLE
[RxR-VLNCE Challenge] How to get the error log fron RxR leadboard

### ISSUE THREAD

**Issue by MarSaKi** [jacobkrantz/VLN-CE#36]
I have tried some times to submmit our [results.](https://ai.google.com/research/rxr/habitat)
But the status of our attempts are error. (We have used the standard RxR task config.)
I want to know if there is any way to check the error log file?

Thanks for your attention to this matter!
Best regards,

**Comment by jacobkrantz** [comment]
Hi, the leaderboard does not produce error logs for user submissions. We can look into the issue on our end if you send us your submission file. Please email your submission to rxrvln@google.com for us to test. Thank you!

**Comment by MarSaKi** [comment]
Thanks for your quick reply !
