### ISSUE TITLE
The ddppo download link is broken.

### ISSUE THREAD

**Issue by sunqiang85** [jacobkrantz/VLN-CE#44]
"Baseline models encode depth observations using a ResNet pre-trained on PointGoal navigation. Those weights can be downloaded from [here](https://github.com/facebookresearch/habitat-lab/tree/master/habitat_baselines/rl/ddppo) (672M). Extract the contents to data/ddppo-models/{model}.pth." The ddppo download link is broken.

**Comment by jacobkrantz** [comment]
Fixed. Thanks for letting me know!
