### ISSUE TITLE
habitat-sim problem: Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found

### ISSUE THREAD

**Issue by FutureGoingOn** [jacobkrantz/VLN-CE#49]
When I want to try this code, I must install the **haistat-sim** first, but I encounter a big bug. I followed the issue in the [**haistat sim No.288** ](https://github.com/facebookresearch/habitat-sim/issues/288), but it did not solve my problem. Who has some good suggestions?

**I follow the codes:**

```
conda install -c aihabitat -c conda-forge habitat-sim=0.1.7 headless

git clone --branch v0.1.7 git@github.com:facebookresearch/habitat-lab.git

python -m pip install -r requirements.txt
python -m pip install -r habitat_baselines/rl/requirements.txt
python -m pip install -r habitat_baselines/rl/ddppo/requirements.txt
python setup.py develop --all

wget http://dl.fbaipublicfiles.com/habitat/habitat-test-scenes.zip
unzip habitat-test-scenes.zip

python examples/example.py
```

**Then get the following errors:**

> I1010 18:31:04.590993 11476 SceneGraph.h:93] Created DrawableGroup:
Platform::WindowlessEglApplication::tryCreateContext(): unable to find EGL device for CUDA device 0
WindowlessContext: Unable to create windowless context

**OR**

> I1207 08:31:49.998020  1190 SceneGraph.h:93] Created DrawableGroup: 
Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found, likely a driver issue; enable --magnum-gpu-validation to see additional info
WindowlessContext: Unable to create windowless context

I can confirm that my NVIDIA driver is correct, cuda is also OK, since I can run other CNN-related codes well.

In fact, I can run habitat **correctly in my PC,** but I have always encountered this error in docker of my server. 

I have tried multiple versions of the NVIDIA driver and cuda, as well as some possible dependent lib versions, such as libgl in my server, following [**haistat sim No.288** ](https://github.com/facebookresearch/habitat-sim/issues/288) .

**The following are all the differences I can understand between PC and server's docker:**

with `**ldconfig -N -v | grep libEGL**`, **In the server's docker:**

>  /sbin/ldconfig.real: Can't stat /usr/local/cuda/compat/lib: No such file or directory
> /sbin/ldconfig.real: Path `/usr/local/cuda/lib64' given more than once
> /sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib: No such file or directory
> /sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib64: No such file or directory
> /sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
> /sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvcuvid.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libcuda.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.440.100 is empty, not checked.
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libvdpau_nvidia.so.440.100 is empty, not checked.
>         libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
>         libEGL.so.1 -> libEGL.so.1.0.0
>         libEGL_nvidia.so.0 -> libEGL_nvidia.so.470.141.03

**BUT in the PC:**

> /sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
> /sbin/ldconfig.real: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link
> /sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.23.so is the dynamic linker, ignoring
>         libEGL.so.1 -> libEGL.so.1.1.0
>         libEGL_nvidia.so.0 -> libEGL_nvidia.so.440.44

It seems to be a problem from this difference? Who has some good solutions, please help me. Thanks.

**Comment by gmm0325** [comment]
Have you solve this problem? I reported a similar error

**Comment by francesco-taioli** [comment]
I was able to fix the issue, see [here](https://github.com/facebookresearch/habitat-sim/issues/1671#issuecomment-1464877434)

**Comment by gmm0325** [comment]
I sincerely thank you for your efficient and helpful guidance and help. Your answer has solved my problem. I wish you all the best in your study and life.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jacobkrantz/VLN-CE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jacobkrantz/VLN-CE] habitat-sim problem: Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found (Issue #49)





 
I was able to fix the issue, see here

**Comment by francesco-taioli** [comment]
@FutureGoingOn I found very useful[ this guide](https://www.murhabazi.com/install-nvidia-driver), it explains the process involved.

**Comment by FutureGoingOn** [comment]
@francesco-taioli Thinks for the nice guide! But I have tried similar steps as described in the guide many times, including **different driver and cuda versions**, and the errors are consistent. The error is as follows:
`Created DrawableGroup: 
eglQueryDevicesEXT(): EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
Platform::WindowlessEglApplication::tryCreateContext(): no EGL devices found, likely a driver issue
WindowlessContext: Unable to create windowless context`.

The origin error is like `Created DrawableGroup: 
Platform::WindowlessEglApplication::tryCreateContext(): unable to find EGL device for CUDA device 0
WindowlessContext: Unable to create windowless context`

Still, I can run this habitat correctly in my PC, but I have always encountered the two errors **in the docker of my server**.

**Comment by francesco-taioli** [comment]
Please take a look at this [issue](https://github.com/facebookresearch/habitat-sim/issues/1671#issuecomment-1464877434), they have the same error: `no EGL devices found` 
I think you should to install the correct nvidia-driver also in your docker container

**Comment by MultyXu** [comment]
Hi @francescotaioli, have you figure out the way to run the example.py in the container on server? I have the exactly the same issue here.

**Comment by francescotaioli** [comment]
Hi @MultyXu, please see the links in the messages above. Usually, the process to solve the issue is listed there. Otherwise, if you cannot solve the issue, it's better to open an issue on habitat side.
