### ISSUE TITLE
How to get  panoramas ?

### ISSUE THREAD

**Issue by Mingxiao-Li** [jacobkrantz/VLN-CE#5]
Hi, I find when I use env.observation I only get one image. However, the CMA model should use panorams, right ? Is ther someone konws how to get the panoramas ?

**Comment by jacobkrantz** [comment]
Hi @Mingxiao-Li, neither the Seq2Seq or CMA models from the VLN-CE paper use panoramas. Both just use the egocentric single frame that you mention. If you would like to build different models that observe panoramas, I suggest looking into recent and ongoing development in Hab-Sim and Hab-Lab. In particular, there is some 360 support using the pipeline developed at https://github.com/facebookresearch/habitat-lab/pull/478 and a fisheye camera here https://github.com/facebookresearch/habitat-lab/pull/486. The API for these features may change as this is an active area of development.

**Comment by Mingxiao-Li** [comment]
Hi,@jacobkrantz, ok, many thanks for your answering.
