### ISSUE TITLE
RGB image quality

### ISSUE THREAD

**Issue by chen-judge** [jacobkrantz/VLN-CE#54]
Hi Jacob,

I found that the image quality rendered by Habitat seems to be inferior to that of the MP3D simulator. Do you have any suggestions for improving the image quality? Thank you!

Here is a comparison of these two simulators. I set WIDTH=512, HEIGHT=512, HFOV=90, and save the image as the PNG format in Habitat:
![5 030_0 172_rgb](https://github.com/jacobkrantz/VLN-CE/assets/31342901/271e1a4c-8c23-4e26-8472-9d2cee1958c3)
While the MP3D is better:
![15](https://github.com/jacobkrantz/VLN-CE/assets/31342901/9af5b19b-655a-4e7c-aa93-eb55cca9e689)

**Comment by missTL** [comment]
Hello, may I ask how to improve the quality of the image?
