### ISSUE TITLE
The motivation for using discrete actions as ground truth

### ISSUE THREAD

**Issue by goodstudent9** [jacobkrantz/VLN-CE#62]
Hello，

I've noticed that the actions in the training data are all discrete, with each action being a fixed minimum action unit. However, since we are in a continuous environment, why not construct more continuous actions? For example, why not directly construct an action for moving forward 5 meters, instead of breaking it down into multiple actions of moving forward 0.5 meters in the ground truth data? I would like to know the motivation behind setting the ground truth to a fixed action space when constructing the data.
Thank you for your response.

Best Wishes
Johan

**Comment by jacobkrantz** [comment]
Hi Johan,

The original VLN-CE work used discrete actions as it was the prevailing paradigm at the time; continuous actions such as velocity control were not yet mature in the simulation platform and learning policies for low-dimensional discrete actions had demonstrated success in related visual navigation domains. "Ground truth" data and the resulting optimal trajectories will depend on the chosen action space, so the choices we made should not be seen as prescriptive.

For reference, some examples of other "action spaces" in VLN: velocity control in [Robo-VLN](https://arxiv.org/abs/2104.10674), variable waypoint prediction in [Waypoint-VLN](https://arxiv.org/abs/2110.02207), and graph prediction in [ETPNav](https://arxiv.org/abs/2304.03047).
